
#DB connection
url=jdbc:postgresql://localhost:5432/database1
username=postgres
password=root
driver=org.postgresql.Driver


#Liquibase connection
changeLogFile=src/db/changelog/db.changelog-master.xml

