# No 'db.' prefix, no quotes
driver=org.postgresql.Driver
url=jdbc:postgresql://localhost:5432/testliq1
username=postgres
password=root

# The path to your master changelog
changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml

# ---- Logging ----
logLevel=info